version: '3.5'

services:
  2hol_build_env:
    build: ./src
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./2hol:/src:ro
      - ./output:/output

